spring:
  application:
    name: taco-cloud
  data:
    rest:
     base-path: /api		
  artemis:
    broker-url: tcp://artemis.tacocloud.com
    user: tacoweb
    password: 13tm31n
  jms:
    template:
      default-destination: tacocloud.order.queue
  boot:
    admin:
      client:
        url:
        - http://localhost:9090
taco:
  orders:
    page-size: 10
management:
  info:
    env:
      enabled: true
    git:
      mode: full
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
         - '*'
        exclude:
        - threaddump
        - heapdump
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
info:
  contact:
    email: support@tacocloud.com
    phone: 822-625-6831
server:
  port: 8081