spring:
  application:
    name: taco-cloud
  data:
    rest:
     base-path: /api		
  artemis:
    broker-url: tcp://artemis.tacocloud.com
    user: tacoweb
    password: 13tm31n
taco:
  orders:
    page-size: 10